### ISSUE TITLE
inconsistent prefix syntax for asserting prefixes

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#11]
```yaml
prefixes:
  SNTC_exact_mixs_usages:
    prefix_prefix: SNTC_exact_mixs_usages
    prefix_reference: http://example.com/SNTC_exact_mixs_usages/
  linkml: https://w3id.org/linkml/
  mixs.vocab: https://w3id.org/mixs/vocab/
  MIXS: https://w3id.org/mixs/terms/
  MIGS: https://w3id.org/mixs/migs/
```
