### ISSUE TITLE
permissible_values - attribute text value (growth_facility) does not match key (field)

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#93]
```sell
poetry run enum_annotator \
	--modelfile target/soil_biosample_modular.yaml \
	--requested_enum_name fao_class_enum \
	--ontology_string ENVO \
	--max_cosine 0.1  > target/temp1.yaml 2>> target/annotation.log
```

only when `schema.enums[suffixed_name] = temp_enum` in `linkml_round_trips/modular_gd.py`

**Comment by turbomam** [comment]
```
  growth_facility_enum:
    name: growth_facility_enum
    permissible_values:
      field:
        text: growth_facility
      field_incubation:
        text: growth_facility
      growth_chamber:
        text: growth_facility
      open_top_chamber:
        text: growth_facility
      greenhouse:
        text: growth_facility
      experimental_garden:
        text: growth_facility
      lab_incubation:
        text: growth_facility
      glasshouse:
        text: growth_facility
      other:
        text: growth_facility
```
